query PageQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        ... on Document {
          id
          _values
          _sys {
            filename
          }
        }
        ...Template1Author
        ...Template2Author
      }
    }
  }
}

query ContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    ...Template1Author
    ...Template2Author
  }
}